#!/usr/bin/env python3
"""Build a per-card kana/romaji search index for every registered expression form."""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import tempfile
import unicodedata
from collections import defaultdict
from pathlib import Path

from pykakasi import kakasi

ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / "grammar-search-readings.js"
KANJI = re.compile(r"[一-龯々]")
WRAPPERS = re.compile(r"[\s　、，。．,.。:：;；/／|｜「」『』（）()【】\[\]{}<>《》〈〉・~〜～…\-]+")
PARENTHETICAL = re.compile(r"[（(【\[].*?[）)】\]]")
SIMPLIFIED_ONLY = set("书词动样态词汇项关义见复习终结规则显拟证实处标称为与个门两东业严乐乡买争于亏云仅从众优会传伤体写击刚别制办务劝势区协却厂厅历厉压厌参双发变叠叶号后听吗单卖卫语谦")

# pykakasi cannot infer the intended reading of isolated homographs.  These
# overrides come from the expression itself and the source grammar books.
MANUAL_READINGS: dict[tuple[str, str], list[str]] = {
    ("basis-7-とおり-どおり", "通り"): ["とおり"],
    ("time-5-たびに", "度に"): ["たびに"],
    ("sequence-9-間-間に", "間"): ["あいだ"],
    ("sequence-9-間-間に", "間に"): ["あいだに"],
    ("result-7-末に", "末に"): ["すえに"],
    ("time-16-や-や否や", "や否や"): ["やいなや"],
    ("contrast-8-は別として", "は別として"): ["はべつとして"],
    ("means-2-を通して", "を通して"): ["をとおして"],
    ("means-2-を通して", "を通した"): ["をとおした"],
    ("means-5-方", "方"): ["かた"],
    ("difficulty-4-得る-得ない", "得る"): ["える", "うる"],
    ("difficulty-4-得る-得ない", "得ない"): ["えない"],
    ("desire-15-に堪えない", "に堪えない"): ["にたえない"],
    ("evaluation-12-に堪える-に堪えない", "に堪える"): ["にたえる"],
    ("evaluation-12-に堪える-に堪えない", "に堪えない"): ["にたえない"],
    ("range-3-を皮切りに", "を皮切りに"): ["をかわきりに"],
    ("respect-7-受身形", "受身形"): ["うけみけい"],
    ("respect-8-使役形", "使役形"): ["しえきけい"],
    ("respect-9-使役受身形", "使役受身形"): ["しえきうけみけい"],
    ("advice-6-命令形-禁止形", "命令形"): ["めいれいけい"],
    ("advice-6-命令形-禁止形", "禁止形"): ["きんしけい"],
}


def node_binary() -> str:
    binary = os.environ.get("NODE_BINARY") or shutil.which("node")
    if not binary:
        raise SystemExit("Node.js was not found. Set NODE_BINARY to a usable node executable.")
    return binary


def compact(value: str) -> str:
    return WRAPPERS.sub("", unicodedata.normalize("NFKC", str(value or "")).lower())


def load_cards() -> list[dict]:
    with tempfile.NamedTemporaryFile("w", suffix=".mjs", delete=False, encoding="utf-8") as handle:
        handle.write(
            """
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
const source = await readFile('content-data.js', 'utf8');
const context = { console };
vm.createContext(context);
const snapshot = vm.runInContext(`${source}
JSON.stringify(GRAMMAR_GROUPS.flatMap((group) => group.expressions.map((item) => ({
  id: item.id, pattern: item.pattern, variants: item.variants || []
}))))`, context);
process.stdout.write(snapshot);
"""
        )
        script = handle.name
    try:
        result = subprocess.run([node_binary(), script], cwd=ROOT, text=True, check=True, capture_output=True)
        return json.loads(result.stdout)
    finally:
        Path(script).unlink(missing_ok=True)


def expression_forms(card: dict) -> list[str]:
    seen: set[str] = set()
    forms: list[str] = []
    for raw in [card.get("pattern", ""), *(card.get("variants") or [])]:
        # Strip explanatory parentheses before splitting.  Otherwise a slash or
        # middle dot inside e.g. 「ばかり（数量/程度）」 leaks labels such as
        # 「数量」 into the kana index as if they were expression variants.
        expression = PARENTHETICAL.sub("", str(raw))
        for part in re.split(r"[／/・|｜]", expression):
            candidate = part
            key = compact(candidate)
            if key and key not in seen:
                seen.add(key)
                forms.append(candidate)
    return forms


def hira_for(text: str, converter) -> str:
    return "".join(token["hira"] for token in converter.convert(text))


def main() -> None:
    converter = kakasi()
    by_card: dict[str, dict[str, list[str]]] = {}
    by_surface: dict[str, set[str]] = defaultdict(set)
    kanji_forms = 0

    for card in load_cards():
        card_readings: dict[str, list[str]] = {}
        for form in expression_forms(card):
            surface = compact(form)
            if not KANJI.search(surface) or any(char in SIMPLIFIED_ONLY for char in surface):
                continue
            readings = MANUAL_READINGS.get((card["id"], surface)) or [compact(hira_for(form, converter))]
            readings = [reading for reading in readings if reading and reading != surface and not KANJI.search(reading)]
            if not readings:
                continue
            card_readings[surface] = readings
            by_surface[surface].update(readings)
            kanji_forms += 1
        if card_readings:
            by_card[card["id"]] = card_readings

    lines = [
        "// Generated by scripts/generate-grammar-search-readings.py. Do not edit manually.",
        "// Every registered kanji expression receives a bidirectional kana/romaji search channel.",
        f"globalThis.GRAMMAR_SEARCH_READINGS = Object.freeze({json.dumps(by_card, ensure_ascii=False, separators=(',', ':'))});",
        f"globalThis.GRAMMAR_QUERY_READINGS = Object.freeze({json.dumps({key: sorted(values) for key, values in sorted(by_surface.items())}, ensure_ascii=False, separators=(',', ':'))});",
        "",
    ]
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps({"cards": len(by_card), "kanjiForms": kanji_forms, "output": str(OUT_PATH)}, ensure_ascii=False))


if __name__ == "__main__":
    main()
