#!/usr/bin/env python3
"""Generate browser-side ruby readings from every Japanese learning field."""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import tempfile
from collections import defaultdict
from pathlib import Path

from pykakasi import kakasi

ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / 'furigana-data.js'
KANJI = re.compile(r'[一-龯々]')
# These simplified-only characters identify Chinese explanatory text. It must
# never be treated as Japanese and given a misleading ruby reading.
SIMPLIFIED_ONLY = set('书词动样态词汇项关义见复习终结规则显拟证实处标称将为与个门两东业严乐乡买争于亏云仅从众优会伟传伤伦体余佛作侧侦侣儿党兰兴养兽写击刚别制剑剂办务劝势勋区协却厂厅历厉压厌参双发变叠叶号后听吗吕单卖卫')


def node_binary() -> str:
    binary = os.environ.get('NODE_BINARY') or shutil.which('node')
    if not binary:
        raise SystemExit('Node.js was not found. Set NODE_BINARY to a usable node executable.')
    return binary


def load_groups() -> list[dict]:
    with tempfile.NamedTemporaryFile('w', suffix='.mjs', delete=False, encoding='utf-8') as handle:
        handle.write("""
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
const source = await readFile('content-data.js', 'utf8');
const context = { console };
vm.createContext(context);
const snapshot = vm.runInContext(`${source}
JSON.stringify(GRAMMAR_GROUPS.map((group) => ({
  id: group.id, notes: group.notes, rewrites: group.rewrites,
  challenges: group.challenges, expressions: group.expressions
})))`, context);
process.stdout.write(snapshot);
""")
        script = handle.name
    try:
        result = subprocess.run([node_binary(), script], cwd=ROOT, text=True, check=True, capture_output=True)
        return json.loads(result.stdout)
    finally:
        Path(script).unlink(missing_ok=True)


def japanese_fields(groups: list[dict]):
    for group in groups:
        for item in group['expressions']:
            # These are the Japanese strings rendered with renderJapaneseText().
            for key in ('pattern', 'collocation', 'example'):
                yield str(item.get(key, '')), False
            # Connection strings are Chinese explanations with Japanese fragments.
            # Only add mixed kanji-kana tokens from them, never Chinese-only text.
            yield str(item.get('connection', '')), True
        for rewrite in group.get('rewrites', []):
            yield str(rewrite[0]), False
            yield str(rewrite[2]), False
        for challenge in group.get('challenges', []):
            # Prompt is Chinese; target and reference answer are Japanese.
            yield str(challenge[3]), False


def build_readings(groups: list[dict]) -> dict[str, str]:
    converter = kakasi()
    readings: dict[str, set[str]] = defaultdict(set)
    for text, require_kana in japanese_fields(groups):
        for token in converter.convert(text):
            original = token['orig']
            if (
                not KANJI.search(original)
                or not token['hira']
                or any(char in SIMPLIFIED_ONLY for char in original)
                or (require_kana and not re.search(r'[ぁ-ゖァ-ヺー]', original))
            ):
                continue
            readings[original].add(token['hira'])

    conflicts = {word: sorted(values) for word, values in readings.items() if len(values) > 1}
    if conflicts:
        details = '\n'.join(f'{word}: {", ".join(values)}' for word, values in sorted(conflicts.items()))
        raise SystemExit(f'Ambiguous readings require a hand-curated entry:\n{details}')
    return {word: next(iter(values)) for word, values in readings.items()}


def main() -> None:
    readings = build_readings(load_groups())
    lines = [
        '// This file is generated by scripts/generate-furigana-data.py. Do not edit manually.',
        '// Readings are derived only from Japanese learning fields; Chinese explanations are deliberately excluded.',
        'globalThis.AUTO_FURIGANA_MAP = Object.freeze({'
    ]
    lines.extend(
        f'  {json.dumps(word, ensure_ascii=False)}: {json.dumps(reading, ensure_ascii=False)},'
        for word, reading in sorted(readings.items(), key=lambda row: (-len(row[0]), row[0]))
    )
    lines.extend(['});', ''])
    OUT_PATH.write_text('\n'.join(lines), encoding='utf-8')
    print(json.dumps({'entries': len(readings), 'output': str(OUT_PATH)}, ensure_ascii=False))


if __name__ == '__main__':
    main()
